# Generated by Django 4.0 on 2022-01-03 17:09

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('tipo', models.IntegerField(choices=[(-1, 'Débito'), (1, 'Crédito')], default=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Rúbrica',
                'verbose_name_plural': 'Rúbricas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historico', models.CharField(max_length=250, verbose_name='Histórico')),
                ('data', models.DateField(verbose_name='Data')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('rubrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='app.rubrica', verbose_name='Rúbrica')),
            ],
        ),
    ]
