# Generated by Django 4.0 on 2022-01-05 19:40

import app.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'ordering': ['-data', 'rubrica__nome', 'historico'], 'verbose_name': 'Lançamento', 'verbose_name_plural': 'Lançamentos'},
        ),
        migrations.AlterModelOptions(
            name='rubrica',
            options={'ordering': ['nome'], 'verbose_name': 'Rúbrica', 'verbose_name_plural': 'Rúbricas'},
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='historico',
            field=models.CharField(blank=True, max_length=250, verbose_name='Histórico'),
        ),
        migrations.AlterField(
            model_name='lancamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[app.utils.validators.validate_non_zero], verbose_name='Valor'),
        ),
    ]
