# Generated by Django 4.0 on 2022-01-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=20, null=True, unique=True, verbose_name='Matrícula')),
                ('telefone', models.CharField(max_length=20, null=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Associado',
                'verbose_name_plural': 'Associados',
                'ordering': ['nome'],
            },
        ),
    ]
