# Generated by Django 4.0 on 2022-01-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_associado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associado',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
