# Generated by Django 4.0 on 2022-01-06 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_associado_matricula_alter_associado_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=250, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('historico', models.TextField(blank=True, verbose_name='Histórico')),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratacoes', to='app.associado', verbose_name='Associado')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratacoes', to='app.contrato', verbose_name='Contrato')),
            ],
            options={
                'verbose_name': 'Contratação',
                'verbose_name_plural': 'Contratações',
                'ordering': ['associado__nome', 'contrato__nome', 'descricao'],
            },
        ),
    ]
