# Generated by Django 4.0.1 on 2022-01-07 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_competencia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competencia',
            unique_together={('ano', 'mes')},
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vence', models.DateField(verbose_name='Data de Vecimento')),
                ('multa', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Multa')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Saldo')),
                ('data_pgto', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('valor_pgto', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor do Pagamento')),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='app.associado', verbose_name='Associado')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='app.competencia', verbose_name='Competência')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
                'ordering': ['associado__nome', '-competencia__ano', '-competencia__mes'],
                'unique_together': {('associado', 'competencia')},
            },
        ),
    ]
