# Generated by Django 4.0.1 on 2022-01-07 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_competencia_unique_together_mensalidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('contratacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineas', to='app.contratacao', verbose_name='Contratacao')),
                ('mensalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alineas', to='app.mensalidade', verbose_name='Mensalidade')),
            ],
            options={
                'verbose_name': 'Alínea',
                'verbose_name_plural': 'Alíneas',
                'ordering': ['contratacao__contrato__nome'],
                'unique_together': {('mensalidade', 'contratacao')},
            },
        ),
    ]
